### PR TITLE
Add: primitive RFC 8044 datatypes to dict parser

### PR DESCRIPTION
**Pull request by Istvan91**
Only the primitve datatypes (+ maybe concat) was added
to the dictionary parser.

Complex types like the extended or long-extended are
yet to be implemented.

This commit only enables parsing/correctly identifying
the added datatypes. Functions for parsing them from
actual RADIUS packets have yet to be implemented.

### CODE REVIEW

**Comment by Istvan91** [comment]
I'm not 100% sure how to implement the Concat type. The Freeradius dictionary don't treat it as a separate type, but as an "flag". Therefore currently concat types are parsed as ByteStrings.

**Comment by MikhailMS** [comment]
Thank you for the PR @Istvan91 - I'd review and approve asap :)

This one looks a bit more work to go through than #13, so would be a bit longer to approve
In the meantime thou, do you know of the usecase for those new data types? Haven't seen them :)

**Comment by Istvan91** [comment]
Not all of them are new per se, some of them have been in use for quite a while. Originally in VSAs (and have been implemented by FreeRADIUS and/or some proprietary RADIUS Servers), but then they have been used by some Standards/RFCs. All of the implemented datatypes are (in actual) use by RFCs and the test attributes i've added to dict_example are Standard RADIUS Attributes.

There are quite a lot more types in actual use, but only in VSAs. There is an (partial) overview in the freeradius directory of the types in use: https://github.com/FreeRADIUS/freeradius-server/blob/master/share/dictionary/radius/dictionary

AFAIK the "complex" types (which I did not implement), are just to expand the standard space and currently not in use by anyone (though there is an implementation in freeradius).

**Review by MikhailMS — APPROVED** [review]
LGTM

There are def work to be done around namings, so we either support dict as per RFC or as per FreeRADIUS (or allow both approaches)

**Pull request merged**
